name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable
          command: android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
